firebase.bucket-name=davetiye-storage.firebasestorage.app

# Maksimum dosya boyutu (10MB yapt?k, rahat rahat yüklensin)
spring.servlet.multipart.max-file-size=10MB
# Maksimum istek boyutu
spring.servlet.multipart.max-request-size=10MB